### ISSUE TITLE
Configure settings path

### ISSUE THREAD

**Issue by Tasosgemah** [m64p/mupen64plus-gui#17] opened 2017-08-23 02:41 UTC
The emulator saves it's settings in the appdata/roaming folder. Can it be configurable so we can choose where it's saved?

**Comment by cascardian** [comment] 2017-08-23 16:40
Not that I think you're not aware of this, logan, but here's a quick addendum from me just so it doesn't get lost:

To make this a full-blown portable mode, it'd also require being able to set the paths of the _save_, _shaders_ and _cache_/_hires_texture_ (already available via video settings; don't know if this also affects _cache_) folders.

**Comment by loganmc10** [comment] 2017-08-23 17:36
mupen64plus allows you to configure 2 directories: ConfigPath and DataPath. The ConfigPath is where mupen64plus.cfg resides, the DataPath is where the save/shaders/screenshot folder resides. (By default they are both the same, AppData/Roaming/Mupen64plus)

I'll make them both configurable, so that nothing should go in AppData if you have those 2 paths configured for somewhere else.

Like you mentioned, some plugins (like GLideN64) also have some paths configured, like the "txPath" field. It's up to the plugin to determine that path, but they are able to query mupen64plus for the ConfigPath and DataPath locations, so they should use that.

**Comment by scottluker** [comment] 2017-08-23 18:42
Being able to have m64p be able to configure mupen64plus so it's full portable is an important option for me as well. Hopefully the implementation of this path configuration would allow `.\` so it's relative to where m64p is stored.

**Comment by loganmc10** [comment] 2017-08-23 21:17
Ok this is what I've done:

If the directory where mupen64plus-gui.exe is writable, it will store the GUI's config in that directory (plugin selections, etc...). If it's not writable, it stores it in a common area (registry in Windows, ~/.config in Linux, this is how it worked previously)

The Config Directory is now configurable (under "Plugin and Path Selection"). I'm not going to default that to the application's directory, since that may not be writable, so it still defaults to AppData/Roaming on Windows. To address @scottluker's point, I made it so you can either select a directory, or type in there, so you can type ```.\``` if you want and it'll make it the same directory as mupen64plus-gui.exe

Unfortunately I was wrong about the Data Directory, the path where save files and shaders are stored is not configurable in mupen64plus. It is always going to be in AppData/Roaming. This is just how mupen64plus-core works right now (https://github.com/mupen64plus/mupen64plus-core/blob/master/src/osal/files_win32.c#L153)

The build at https://m64p.github.io/ should be updated, please give it a try and let me know, once I hear some feedback I'll close this ticket.

**Comment by Tasosgemah** [comment] 2017-08-24 00:47
Doesn't seem to work when i run the emulator through a frontend like LanchBox. Even though i changed the directory of the setting file to the root folder where the emulator is, when i run the emulator from the frontend it ignores it and uses the default appdata/roaming folder again.

When i run the emulator with it's default UI, it works.

**Comment by loganmc10** [comment] 2017-08-24 00:50
Well ```./``` actually means the current directory, if you launch from a frontend, ```./``` probably means the folder that the LaunchBox is, and if that isn't writable, it will use appdata/roaming. If you want it to use mupen64plus-gui's directory, you probably need to use the absolute path to it.

**Comment by Tasosgemah** [comment] 2017-08-24 00:53
I'm using this path:

G:/Emulators/Nintendo 64/_Emulators/Mupen64plus

G is the letter of my Emulators HDD. It's writable.

**Comment by loganmc10** [comment] 2017-08-24 00:55
hm ok I might know what the issue is, give me a bit to do some testing

**Comment by Tasosgemah** [comment] 2017-08-24 00:58
One more thing... When i run the emulator through the frontend it also opens a console command window along with the game window. This doesn't happen when i run it with the included MupenUI. Dunno if this has anything to do with something.

**Comment by loganmc10** [comment] 2017-08-24 00:59
When you run it though LaunchBox, what is the command you are using? Are you launching mupen64plus.exe or mupen64plus-gui.exe ?

**Comment by Tasosgemah** [comment] 2017-08-24 01:01
I don't use any commands. I run mupen64plus.exe.

**Comment by loganmc10** [comment] 2017-08-24 01:02
You should run mupen64plus-gui.exe

All of these changes only apply to mupen64plus-gui.exe, that is what this GitHub page is for.

mupen64plus.exe is a separate program, the code is here: https://github.com/mupen64plus/mupen64plus-ui-console

mupen64plus-gui.exe supports launching games from an argument as well, for instance ```mupen64plus-gui.exe myrom.n64```

**Comment by Tasosgemah** [comment] 2017-08-24 01:03
Yeah i just figured it out. Thanks. Works ok now.

**Comment by scottluker** [comment] 2017-08-24 08:54
The the saves folder if I manually set it to `.\save\` within mupen64plus.cfg then it will save to m64p local directory otherwise left as default it will still to go appdata.

**Comment by loganmc10** [comment] 2017-08-24 15:15
Oh I didn't even realize there was an option for that. So can I close this then? It's sufficiently portable now?

**Comment by scottluker** [comment] 2017-08-24 15:35
Well the config file says: "If this is blank, the default value of ${UserConfigPath}/save will be used"  but when `SaveSRAMPath` is left blank it uses the appdata folder rather than the config folder.

**Comment by loganmc10** [comment] 2017-08-24 15:40
I know that's misleading and makes it seem like it's configurable, in reality it actually uses UserDataPath:

https://github.com/mupen64plus/mupen64plus-core/blob/5c386fd741e776a499b67a8d867fc4cdd8e927d3/src/main/main.c#L141

Which is not configurable, and points to appdata/roaming on Windows, and ~/.local/share/mupen64plus on Linux.

These are issues that could be sorted out in mupen64plus-core, but it's not something I can change within the GUI

**Comment by scottluker** [comment] 2017-08-24 15:42
Ah ok, yeah this issue can be closed as the other issues with saves and shaders are to do with the mupen64plus-core. Thank you for your work though.

**Closed** 2017-08-24 15:43 UTC

**Comment by StenApp** [comment] 2017-11-26 20:08
@loganmc10  
Is it possible to set the 
`~/.local/share/mupen64plus` on Linux to this under macOS:?
`~/Library/Application Support/mupen64plus`

Since this is the path apple programs create in user folder

**Comment by loganmc10** [comment] 2017-11-26 20:18
That path is set by mupen64plus-core, not the gui:

https://github.com/mupen64plus/mupen64plus-core/blob/master/src/osal/files_unix.c#L235-L254

Basically mupen64plus treats OSX as "Unix" the same as Linux, so most the code is the same for both OSes
